"""add_uploaded_documents_table

Revision ID: 493a1f811677
Revises: a3f8c2e91b4d
Create Date: 2026-05-16 12:07:37.307379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493a1f811677'
down_revision: Union[str, None] = 'a3f8c2e91b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_documents',
    sa.Column('file_id', sa.String(length=100), nullable=False, comment='文件唯一标识(UUID)'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='原始文件名'),
    sa.Column('file_ext', sa.String(length=20), nullable=False, comment='文件扩展名(含点)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment='文件在服务器上的存储路径'),
    sa.Column('text_length', sa.Integer(), nullable=False, comment='提取的文本字数'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='上传者用户ID(游客为null)'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='上传者姓名(冗余存储便于查询)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: uploaded/proofread/deleted'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_documents_file_id'), 'uploaded_documents', ['file_id'], unique=True)
    op.alter_column('proofread_records', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='记录类型: text/document/polish',
               existing_comment='校对类型: text/document',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proofread_records', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='校对类型: text/document',
               existing_comment='记录类型: text/document/polish',
               existing_nullable=False)
    op.drop_index(op.f('ix_uploaded_documents_file_id'), table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    # ### end Alembic commands ###
