"""add_extracted_text_to_uploaded_documents

Revision ID: 96739972ca65
Revises: 493a1f811677
Create Date: 2026-05-16 12:47:18.717458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96739972ca65'
down_revision: Union[str, None] = '493a1f811677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_documents', sa.Column('extracted_text', sa.Text(), nullable=True, comment='提取的文本内容(持久化存储，避免内存缓存丢失)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_documents', 'extracted_text')
    # ### end Alembic commands ###
