"""add_audit_logs_table

Revision ID: dd92b5173a1f
Revises: 
Create Date: 2026-05-14 08:56:15.248544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dd92b5173a1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='操作类型: polish/proofread_text/proofread_doc/view_history/login_success/login_failed/logout'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID（游客为NULL）'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='用户名快照'),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='工号快照'),
    sa.Column('is_guest', sa.Boolean(), nullable=False, comment='是否游客'),
    sa.Column('client_ip', sa.String(length=45), nullable=False, comment='客户端IP（支持IPv6）'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器User-Agent'),
    sa.Column('device_type', sa.String(length=20), nullable=True, comment='设备类型: desktop/mobile/tablet'),
    sa.Column('input_text', sa.Text(), nullable=True, comment='用户输入文本'),
    sa.Column('input_length', sa.Integer(), nullable=False, comment='输入文本字符数'),
    sa.Column('output_text', sa.Text(), nullable=True, comment='AI输出结果'),
    sa.Column('output_length', sa.Integer(), nullable=False, comment='输出文本字符数'),
    sa.Column('extra_params', sa.JSON(), nullable=True, comment='额外参数（润色风格、校对类型、领域等）'),
    sa.Column('file_id', sa.String(length=100), nullable=True, comment='文档校对关联的文件ID'),
    sa.Column('file_name', sa.String(length=500), nullable=True, comment='源文件名'),
    sa.Column('file_path', sa.String(length=1000), nullable=True, comment='服务器文件存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='操作状态: success/failed/processing'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='操作耗时（毫秒）'),
    sa.Column('token_usage', sa.JSON(), nullable=True, comment='AI Token消耗量'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_type', 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_client_ip', 'audit_logs', ['client_ip'], unique=False)
    op.create_index('ix_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_is_guest', 'audit_logs', ['is_guest'], unique=False)
    op.create_index('ix_audit_status', 'audit_logs', ['status'], unique=False)
    op.create_index('ix_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_status', table_name='audit_logs')
    op.drop_index('ix_audit_is_guest', table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_client_ip', table_name='audit_logs')
    op.drop_index('ix_audit_action_type', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
